# Generated by Django 6.0.5 on 2026-06-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO game_product (name, price, description, inventory, last_updated) VALUES ('astro', 19.99, 'A fun game for all ages', 100, '2026-06-03 11:03:00');
            """,
            """         
            DELETE FROM game_product WHERE name = 'astro';
            """
        )
    ]
